CAUSAL_ANALYSIS_FAILED = "Causal analysis failed. Please try again later."
CAUSAL_ANALYSIS_EMAIL_BODY = "Please find the causal analysis results in the pdf document attached to this email."
EMAIL = "admin@causalbench.org"
SEND_AS_EMAIL = "register@causalbench.org"
REPLY_TO_ADDRESS = "contact@causalbench.org"
EMAIL_PASSWORD = "zrwakioxcinloiht"